server:
    port: ${PORT:8082}
application:
    jwt:
        secretKey: ${SECRET_KEY:securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure}
        tokenPrefix: "Bearer "
        tokenExpirationAfterDays: 10

spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:squeaker}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        driverClassName: org.postgresql.Driver

logging:
    level:
        com:
            hamsterbusters:
                squeaker: DEBUG